package com.pojo;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_message.message_id
     *
     * @mbg.generated
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_message.message_time
     *
     * @mbg.generated
     */
    private Date messageTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_message.message_ip
     *
     * @mbg.generated
     */
    private String messageIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_message.message_ua
     *
     * @mbg.generated
     */
    private String messageUa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_message.message_user_id
     *
     * @mbg.generated
     */
    private Integer messageUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_message.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_message.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_message.message_info
     *
     * @mbg.generated
     */
    private String messageInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_message.message_id
     *
     * @return the value of oa_message.message_id
     *
     * @mbg.generated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_message.message_id
     *
     * @param messageId the value for oa_message.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_message.message_time
     *
     * @return the value of oa_message.message_time
     *
     * @mbg.generated
     */
    public Date getMessageTime() {
        return messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_message.message_time
     *
     * @param messageTime the value for oa_message.message_time
     *
     * @mbg.generated
     */
    public void setMessageTime(Date messageTime) {
        this.messageTime = messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_message.message_ip
     *
     * @return the value of oa_message.message_ip
     *
     * @mbg.generated
     */
    public String getMessageIp() {
        return messageIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_message.message_ip
     *
     * @param messageIp the value for oa_message.message_ip
     *
     * @mbg.generated
     */
    public void setMessageIp(String messageIp) {
        this.messageIp = messageIp == null ? null : messageIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_message.message_ua
     *
     * @return the value of oa_message.message_ua
     *
     * @mbg.generated
     */
    public String getMessageUa() {
        return messageUa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_message.message_ua
     *
     * @param messageUa the value for oa_message.message_ua
     *
     * @mbg.generated
     */
    public void setMessageUa(String messageUa) {
        this.messageUa = messageUa == null ? null : messageUa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_message.message_user_id
     *
     * @return the value of oa_message.message_user_id
     *
     * @mbg.generated
     */
    public Integer getMessageUserId() {
        return messageUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_message.message_user_id
     *
     * @param messageUserId the value for oa_message.message_user_id
     *
     * @mbg.generated
     */
    public void setMessageUserId(Integer messageUserId) {
        this.messageUserId = messageUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_message.gmt_create
     *
     * @return the value of oa_message.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_message.gmt_create
     *
     * @param gmtCreate the value for oa_message.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_message.gmt_modified
     *
     * @return the value of oa_message.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_message.gmt_modified
     *
     * @param gmtModified the value for oa_message.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_message.message_info
     *
     * @return the value of oa_message.message_info
     *
     * @mbg.generated
     */
    public String getMessageInfo() {
        return messageInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_message.message_info
     *
     * @param messageInfo the value for oa_message.message_info
     *
     * @mbg.generated
     */
    public void setMessageInfo(String messageInfo) {
        this.messageInfo = messageInfo == null ? null : messageInfo.trim();
    }
}