package com.pojo;

import java.util.Date;

public class Signin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_signin.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_signin.signin_user_id
     *
     * @mbg.generated
     */
    private Integer signinUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_signin.signin_time
     *
     * @mbg.generated
     */
    private Date signinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_signin.signin_ip
     *
     * @mbg.generated
     */
    private String signinIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_signin.signin_ua
     *
     * @mbg.generated
     */
    private String signinUa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_signin.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_signin.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_signin.id
     *
     * @return the value of oa_signin.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_signin.id
     *
     * @param id the value for oa_signin.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_signin.signin_user_id
     *
     * @return the value of oa_signin.signin_user_id
     *
     * @mbg.generated
     */
    public Integer getSigninUserId() {
        return signinUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_signin.signin_user_id
     *
     * @param signinUserId the value for oa_signin.signin_user_id
     *
     * @mbg.generated
     */
    public void setSigninUserId(Integer signinUserId) {
        this.signinUserId = signinUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_signin.signin_time
     *
     * @return the value of oa_signin.signin_time
     *
     * @mbg.generated
     */
    public Date getSigninTime() {
        return signinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_signin.signin_time
     *
     * @param signinTime the value for oa_signin.signin_time
     *
     * @mbg.generated
     */
    public void setSigninTime(Date signinTime) {
        this.signinTime = signinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_signin.signin_ip
     *
     * @return the value of oa_signin.signin_ip
     *
     * @mbg.generated
     */
    public String getSigninIp() {
        return signinIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_signin.signin_ip
     *
     * @param signinIp the value for oa_signin.signin_ip
     *
     * @mbg.generated
     */
    public void setSigninIp(String signinIp) {
        this.signinIp = signinIp == null ? null : signinIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_signin.signin_ua
     *
     * @return the value of oa_signin.signin_ua
     *
     * @mbg.generated
     */
    public String getSigninUa() {
        return signinUa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_signin.signin_ua
     *
     * @param signinUa the value for oa_signin.signin_ua
     *
     * @mbg.generated
     */
    public void setSigninUa(String signinUa) {
        this.signinUa = signinUa == null ? null : signinUa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_signin.gmt_create
     *
     * @return the value of oa_signin.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_signin.gmt_create
     *
     * @param gmtCreate the value for oa_signin.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_signin.gmt_modified
     *
     * @return the value of oa_signin.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_signin.gmt_modified
     *
     * @param gmtModified the value for oa_signin.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}