package com.pojo;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.student_number
     *
     * @mbg.generated
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.is_signin_today
     *
     * @mbg.generated
     */
    private Integer isSigninToday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.small_group
     *
     * @mbg.generated
     */
    private Integer smallGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.config_permission
     *
     * @mbg.generated
     */
    private Integer configPermission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csti_user.image_path
     *
     * @mbg.generated
     */
    private String imagePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.id
     *
     * @return the value of csti_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.id
     *
     * @param id the value for csti_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.student_number
     *
     * @return the value of csti_user.student_number
     *
     * @mbg.generated
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.student_number
     *
     * @param studentNumber the value for csti_user.student_number
     *
     * @mbg.generated
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.name
     *
     * @return the value of csti_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.name
     *
     * @param name the value for csti_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.password
     *
     * @return the value of csti_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.password
     *
     * @param password the value for csti_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.group_id
     *
     * @return the value of csti_user.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.group_id
     *
     * @param groupId the value for csti_user.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.is_signin_today
     *
     * @return the value of csti_user.is_signin_today
     *
     * @mbg.generated
     */
    public Integer getIsSigninToday() {
        return isSigninToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.is_signin_today
     *
     * @param isSigninToday the value for csti_user.is_signin_today
     *
     * @mbg.generated
     */
    public void setIsSigninToday(Integer isSigninToday) {
        this.isSigninToday = isSigninToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.small_group
     *
     * @return the value of csti_user.small_group
     *
     * @mbg.generated
     */
    public Integer getSmallGroup() {
        return smallGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.small_group
     *
     * @param smallGroup the value for csti_user.small_group
     *
     * @mbg.generated
     */
    public void setSmallGroup(Integer smallGroup) {
        this.smallGroup = smallGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.config_permission
     *
     * @return the value of csti_user.config_permission
     *
     * @mbg.generated
     */
    public Integer getConfigPermission() {
        return configPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.config_permission
     *
     * @param configPermission the value for csti_user.config_permission
     *
     * @mbg.generated
     */
    public void setConfigPermission(Integer configPermission) {
        this.configPermission = configPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.gmt_create
     *
     * @return the value of csti_user.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.gmt_create
     *
     * @param gmtCreate the value for csti_user.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.gmt_modified
     *
     * @return the value of csti_user.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.gmt_modified
     *
     * @param gmtModified the value for csti_user.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csti_user.image_path
     *
     * @return the value of csti_user.image_path
     *
     * @mbg.generated
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csti_user.image_path
     *
     * @param imagePath the value for csti_user.image_path
     *
     * @mbg.generated
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }
}