package com.mapper;

import com.pojo.Config;
import com.pojo.ConfigExample;

import java.util.List;

public interface ConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    int insert(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    int insertSelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    List<Config> selectByExampleWithBLOBs(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    List<Config> selectByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    Config selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Config record);
}